# [Optional] Practice with simulating random outcomes

Use these code exercises to practice working with random variables! These code blocks are optional, and you may choose to spend more or less time with them depending on your level of familiarity with Python.

## Exercise 1: Uniform distribution sampling

Create a sample of five random numbers drawn from a uniform distribution between 0 and 1.

### Instructions

- Create a sample of five random numbers using `np.random.rand()` and save it to a variable.
- Print out the array using `print()`.

In [ ]:
import numpy as np

### START CODE HERE ###

### END CODE HERE ###

**Expected output:**

(the numbers in the output will vary as they are random numbers. but they should all be between 0 and 1)

```
[ 0.80611653 0.86038033 0.70581575 0.63032033 0.15503143]
```

## Exercise 2: Uniform distribution (2 to 3).

Create a sample of five random numbers drawn from a uniform distribution between 2 and 3.

### Instructions

- You can do this the same way as in the previous exercise, with an additional step where you add 2 to the array, so that all numbers will have their values increased by 2 (moving the interval from (0, 1) to (2, 3)).
- Print out the array using `print()`.

In [ ]:
import numpy as np

### START CODE HERE ###

### END CODE HERE ###

**Expected output:**

(the numbers in the output will vary as they are random numbers. but they should all be between 2 and 3)

```
[ 2.93506879 2.79222991 2.84666148 2.35780786 2.32448338]
```

## Exercise 3: Normal distribution sampling

You want to open a male clothing shop in the Netherlands, which is one of the countries with the tallest people in the world. In order to stock the correct sizes of clothes, you want to simulate a sample of heights. The mean adult male height in the region is reported to be 184 cm with the standard deviation of 7 cm. Create a sample of five random numbers drawn from a normal distribution with a mean of 184 and standard deviation of 7.

### Instructions

- Create a sample of five random numbers using `np.random.normal()` and save it to a variable.
- The numbers should be drawn from a distribution with a mean of 184 and standard deviation of 7.
- Print out the array using `print()`.

In [ ]:
import numpy as np

### START CODE HERE ###

### END CODE HERE ###

**Expected output:**

(the numbers in the output will vary as they are random)

```
[186.11228057 174.13142658 185.57949132 178.36686042 194.2048808]
```

## SOLUTIONS:

## Exercise 1:

```python
random_uniform_sample = np.random.rand(5)
print(random_uniform_sample)
```

## Exercise 2:

```python
random_uniform_sample = np.random.rand(5) + 2
print(random_uniform_sample)
```

## Exercise 3:

```python
random_normal_sample = np.random.normal(184, 7, 5)
print(random_normal_sample)
```